discovery:
  #exclusions:
  # (example) do not search tests in 'ignored_folder' folder
#  - deploy/
#  - gw_bot/
#  - modules/OSBot-AWS
#  - modules/OSBot-browser
#  - modules/osbot-docker-codebuild
#  - modules/OSBot-jira
#  - modules/OSBot-Jupyter
#  - tests/
  #- tests/utils/
engine:
  runtime: pytest